version: "3"
services:
  php:
    build: './php/'
    container_name: test_php
    volumes:
      - ./src/:/var/www/html/

  apache:
    build: './apache/'
    container_name: test_apache
    depends_on:
      - php
    expose: 
      - '80'
    volumes:
      - ./src:/var/www/html
    environment:
      - VIRTUAL_HOST=www.test.local
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=www.test.local
      - LETSENCRYPT_EMAIL=soulblade1403@gmail.com

networks: 
  default:
    external:
      name: reverse-proxy